[jobs.miniplc0-tokenize]
build = {source = "dockerfile", path = "."}
run = [
  "java -jar build/libs/miniplc0java.jar -t $input -o $output",
]

[jobs.miniplc0-analyse]
build = {source = "dockerfile", path = "."}
run = [
  "java -jar build/libs/miniplc0java.jar -a $input -o $output",
]
